#print("Tell me anything")
#anything = input()
#print("Hmm... \"", anything, "\" really?", sep="")
#inPhrase = input("Tell me anything")
#print("Your input was \"",inPhrase,"\"", sep = "")
#base = input("Enetr the base of exponent")
#power = input ("Enter the power of the expoent")
#exponent = str(float(base)**float(power))
#print("The exponent is",exponent)
#Pythagoras theorem with input
leg_a = float(input("Enter the first leg"))
leg_b = float(input("Entr the second leg"))
print("The hypotenous is ", (leg_a**2 + leg_b**2)**0.5)